"""Add author_uid to Video model

Revision ID: 63532f261120
Revises: ea5fc0500867
Create Date: 2025-04-19 11:17:08.665161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63532f261120'
down_revision = 'ea5fc0500867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_uid', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('author_uid')

    # ### end Alembic commands ###
