"""Add danmu model

Revision ID: c942ca80e423
Revises: 
Create Date: 2025-04-19 00:47:01.471375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c942ca80e423'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=20), nullable=False, comment='UP主UID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='UP主名称'),
    sa.Column('follower_count', sa.Integer(), nullable=True, comment='粉丝数'),
    sa.Column('video_count', sa.Integer(), nullable=True, comment='视频数'),
    sa.Column('total_play_count', sa.BigInteger(), nullable=True, comment='总播放量'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authors_uid'), ['uid'], unique=True)

    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bvid', sa.String(length=20), nullable=False, comment='视频BV号'),
    sa.Column('cid', sa.BigInteger(), nullable=True, comment='视频CID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='视频标题'),
    sa.Column('author', sa.String(length=100), nullable=True, comment='UP主名称'),
    sa.Column('video_type', sa.String(length=50), nullable=True, comment='视频分类'),
    sa.Column('play_count', sa.Integer(), nullable=True, comment='播放量'),
    sa.Column('danmaku_count', sa.Integer(), nullable=True, comment='弹幕数'),
    sa.Column('like_count', sa.Integer(), nullable=True, comment='点赞数'),
    sa.Column('coin_count', sa.Integer(), nullable=True, comment='投币数'),
    sa.Column('favorite_count', sa.Integer(), nullable=True, comment='收藏数'),
    sa.Column('share_count', sa.Integer(), nullable=True, comment='分享数'),
    sa.Column('comment_count', sa.Integer(), nullable=True, comment='评论数'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='视频创建时间'),
    sa.Column('crawled_at', sa.DateTime(), nullable=True, comment='爬取时间'),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name='fk_video_author'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_bvid'), ['bvid'], unique=True)
        batch_op.create_index(batch_op.f('ix_videos_cid'), ['cid'], unique=False)

    op.create_table('danmu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_bvid', sa.String(length=20), nullable=False, comment='视频BV号'),
    sa.Column('video_title', sa.String(length=255), nullable=True, comment='视频标题'),
    sa.Column('cid', sa.BigInteger(), nullable=True, comment='视频CID'),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False, comment='弹幕内容'),
    sa.Column('appear_time', sa.Float(), nullable=True, comment='弹幕出现时间(秒)'),
    sa.Column('mode', sa.Integer(), nullable=True, comment='弹幕类型'),
    sa.Column('font_size', sa.Integer(), nullable=True, comment='字体大小'),
    sa.Column('color', sa.Integer(), nullable=True, comment='颜色'),
    sa.Column('send_time', sa.DateTime(), nullable=True, comment='发送时间'),
    sa.Column('user_hash', sa.String(length=50), nullable=True, comment='用户hash'),
    sa.Column('row_id', sa.BigInteger(), nullable=True, comment='行ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name='fk_danmu_video'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('danmu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_danmu_cid'), ['cid'], unique=False)
        batch_op.create_index(batch_op.f('ix_danmu_video_bvid'), ['video_bvid'], unique=False)
        batch_op.create_index(batch_op.f('ix_danmu_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('danmu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_danmu_video_id'))
        batch_op.drop_index(batch_op.f('ix_danmu_video_bvid'))
        batch_op.drop_index(batch_op.f('ix_danmu_cid'))

    op.drop_table('danmu')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_cid'))
        batch_op.drop_index(batch_op.f('ix_videos_bvid'))
        batch_op.drop_index(batch_op.f('ix_videos_author_id'))

    op.drop_table('videos')
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authors_uid'))

    op.drop_table('authors')
    # ### end Alembic commands ###
