"""Fix danmu model relationships

Revision ID: ea5fc0500867
Revises: c942ca80e423
Create Date: 2025-04-19 10:33:26.185930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea5fc0500867'
down_revision = 'c942ca80e423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('danmu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_time', sa.DateTime(), nullable=True, comment='弹幕发送时间'))
        batch_op.drop_index('ix_danmu_cid')
        batch_op.drop_column('send_time')
        batch_op.drop_column('cid')
        batch_op.drop_column('row_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('danmu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('row_id', sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column('cid', sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column('send_time', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_danmu_cid', ['cid'], unique=False)
        batch_op.drop_column('created_time')

    # ### end Alembic commands ###
